feat: complete homework-5
angelinaivanova16/ASTON_TRAINEE_COURSE pull request #5
Opened 2024-04-04 13:51 UTC by angelinaivanova16

2024-04-04 14:03 UTC, ASTON-TRAINEE approved these changes
на классах лаконично и правильно, но теперь попробуй  дополнительно переписать на функциях-конструкторах в качестве допа, а так зачет)

2024-04-07 18:08 UTC, angelinaivanova16 commented
Я добавила решение на функциях-конструкторах. Закомитила.

2024-04-11 07:44 UTC, ASTON-TRAINEE requested changes

2024-04-11 07:44 UTC, ASTON-TRAINEE commented on lection_5/homework.js
> +    this.speak = function() {
методы в прототипах должны быть)

2024-04-27 16:25 UTC, merged